### PR TITLE
Dark mode Enhanced

### PR DESCRIPTION
**Pull request by CXZ7720**
## Describe your Pull Request
The main purpose of this PR is refactoring entire code of  color theme changer.

Migrate dark mode code to React Context based code. This can make change color theme without page refresh.

Merge Dark theme manifest JS script to React Code which was injected direct into HTML <head />

### CODE REVIEW

**Comment by CXZ7720** [comment]
강아지 성능 확실하네

**Comment by Taewan-P** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ

**Review by Taewan-P — APPROVED** [review]
다 정상적으로 작동하네요!

**Comment by Taewan-P** [comment]
버그 발생...

**Pull request merged**
